"""Forecasting service.

Pluggable design: forecasts can be uploaded from external systems (CSV) or
generated by the built-in synthetic models. Every forecast carries
uncertainty: P50, P10/P90 band, error sigma. Scenario paths and
shortfall/excess probabilities are derived on demand.
"""
import datetime as dt
import math

import numpy as np
from sqlalchemy.orm import Session

from .. import models

N_INTERVALS = 48          # half-hourly trading periods (Singapore NEMS)
DT_HOURS = 0.5

RNG = np.random.default_rng(7)

# z-scores for P10 / P90 under a normal error assumption
Z10, Z90 = -1.2816, 1.2816


def _solar_shape(capacity_mw: float, cloud_factor: float = 1.0) -> np.ndarray:
    """Bell-shaped solar profile over 48 half-hour intervals (~07:00–19:00)."""
    out = np.zeros(N_INTERVALS)
    for t in range(N_INTERVALS):
        hour = t * DT_HOURS
        if 7.0 <= hour <= 19.0:
            out[t] = capacity_mw * math.sin(math.pi * (hour - 7.0) / 12.0) ** 1.5 * cloud_factor
    return out


def _demand_shape(base_mw: float, peak_mw: float) -> np.ndarray:
    """Typical SG commercial-industrial load: morning ramp, midday plateau, evening peak."""
    out = np.zeros(N_INTERVALS)
    for t in range(N_INTERVALS):
        hour = t * DT_HOURS
        morning = math.exp(-((hour - 11.0) ** 2) / 18.0)
        evening = math.exp(-((hour - 19.0) ** 2) / 6.0)
        out[t] = base_mw + (peak_mw - base_mw) * max(morning, 0.85 * evening)
    return out


def _usep_shape() -> np.ndarray:
    """USEP forecast: correlated with demand, evening peak premium, midday solar dip."""
    out = np.zeros(N_INTERVALS)
    for t in range(N_INTERVALS):
        hour = t * DT_HOURS
        base = 105.0
        peak = 95.0 * math.exp(-((hour - 19.0) ** 2) / 4.5)       # evening spike
        morning = 35.0 * math.exp(-((hour - 10.0) ** 2) / 10.0)
        midday_dip = -18.0 * math.exp(-((hour - 13.5) ** 2) / 7.0) # solar depresses USEP
        night = -20.0 * math.exp(-((hour - 3.0) ** 2) / 16.0)
        out[t] = base + peak + morning + midday_dip + night
    return out


DEFAULT_SIGMA_PCT = {
    "solar_import": 0.22,     # cross-border import: highest uncertainty
    "solar_local": 0.15,
    "contract_demand": 0.05,
    "usep": 0.18,
    "reserve_price": 0.25,
    "regulation_price": 0.25,
}


def generate_default_forecasts(db: Session, trade_date: dt.date) -> dict:
    """Create the full forecast set for a trading day (idempotent per date/kind)."""
    profiles = {
        "solar_import": _solar_shape(120.0, 0.92),                # 120 MW import, limit applied in optimizer
        "solar_local": _solar_shape(60.0, 0.88),
        "contract_demand": _demand_shape(180.0, 320.0),
        "usep": _usep_shape(),
        "reserve_price": np.maximum(8.0, _usep_shape() * 0.16 - 4.0),
        "regulation_price": np.maximum(12.0, _usep_shape() * 0.20 - 2.0),
    }
    created = {}
    for kind, p50 in profiles.items():
        existing = (db.query(models.ForecastSeries)
                      .filter_by(kind=kind, trade_date=trade_date)
                      .order_by(models.ForecastSeries.id.desc()).first())
        if existing:
            created[kind] = existing.id
            continue
        sigma_pct = DEFAULT_SIGMA_PCT[kind]
        series = models.ForecastSeries(kind=kind, trade_date=trade_date, source="internal")
        db.add(series)
        db.flush()
        for t in range(N_INTERVALS):
            sig = abs(p50[t]) * sigma_pct
            db.add(models.ForecastPoint(
                series_id=series.id, interval=t,
                p50=round(float(p50[t]), 3),
                p10=round(float(max(0.0, p50[t] + Z10 * sig)), 3),
                p90=round(float(p50[t] + Z90 * sig), 3),
                sigma=round(float(sig), 3),
            ))
        created[kind] = series.id
    db.commit()
    return created


def load_forecast(db: Session, kind: str, trade_date: dt.date) -> dict | None:
    series = (db.query(models.ForecastSeries)
                .filter_by(kind=kind, trade_date=trade_date)
                .order_by(models.ForecastSeries.id.desc()).first())
    if not series:
        return None
    pts = sorted(series.points, key=lambda p: p.interval)
    return {
        "series_id": series.id,
        "kind": kind,
        "source": series.source,
        "p50": [p.p50 for p in pts],
        "p10": [p.p10 for p in pts],
        "p90": [p.p90 for p in pts],
        "sigma": [p.sigma for p in pts],
        "actual": [p.actual for p in pts],
    }


def scenario_paths(fc: dict, n_paths: int = 20, seed: int = 11) -> list[list[float]]:
    """Monte-Carlo scenario paths with AR(1)-correlated errors (errors persist intraday)."""
    rng = np.random.default_rng(seed)
    p50 = np.array(fc["p50"])
    sigma = np.array(fc["sigma"])
    rho = 0.85
    paths = []
    for _ in range(n_paths):
        eps = np.zeros(N_INTERVALS)
        eps[0] = rng.normal()
        for t in range(1, N_INTERVALS):
            eps[t] = rho * eps[t - 1] + math.sqrt(1 - rho ** 2) * rng.normal()
        path = np.maximum(0.0, p50 + eps * sigma)
        paths.append([round(float(x), 2) for x in path])
    return paths


def uncertainty_stats(fc: dict, threshold: list[float] | None = None) -> dict:
    """Error distribution + per-interval probability of shortfall/excess vs a threshold
    (threshold defaults to P50, i.e. prob of under/over-shooting the central forecast).
    """
    p50 = np.array(fc["p50"])
    sigma = np.maximum(np.array(fc["sigma"]), 1e-9)
    thr = np.array(threshold) if threshold is not None else p50
    from scipy.stats import norm
    p_short = norm.cdf((thr - p50) / sigma)          # P(actual < threshold)
    p_excess = 1.0 - p_short
    return {
        "prob_shortfall": [round(float(x), 4) for x in p_short],
        "prob_excess": [round(float(x), 4) for x in p_excess],
        "error_distribution": {
            "mean_sigma": round(float(sigma.mean()), 3),
            "max_sigma": round(float(sigma.max()), 3),
            "p10_band_width": round(float((p50 - np.array(fc["p10"])).mean()), 3),
        },
    }


def ingest_uploaded_forecast(db: Session, kind: str, trade_date: dt.date,
                             rows: list[dict]) -> int:
    """Store a forecast uploaded from an external system.
    rows: [{interval, p50, p10?, p90?, sigma?}]  — missing bands are inferred."""
    series = models.ForecastSeries(kind=kind, trade_date=trade_date, source="uploaded")
    db.add(series)
    db.flush()
    default_pct = DEFAULT_SIGMA_PCT.get(kind, 0.15)
    for r in rows:
        p50 = float(r["p50"])
        sig = float(r["sigma"]) if r.get("sigma") not in (None, "") else abs(p50) * default_pct
        p10 = float(r["p10"]) if r.get("p10") not in (None, "") else max(0.0, p50 + Z10 * sig)
        p90 = float(r["p90"]) if r.get("p90") not in (None, "") else p50 + Z90 * sig
        db.add(models.ForecastPoint(series_id=series.id, interval=int(r["interval"]),
                                    p50=p50, p10=p10, p90=p90, sigma=sig))
    db.commit()
    return series.id


def record_actuals(db: Session, kind: str, trade_date: dt.date,
                   actuals: list[float]) -> int:
    """Store actuals against the latest forecast and log forecast errors (learning loop)."""
    series = (db.query(models.ForecastSeries)
                .filter_by(kind=kind, trade_date=trade_date)
                .order_by(models.ForecastSeries.id.desc()).first())
    if not series:
        return 0
    n = 0
    for p in series.points:
        if p.interval < len(actuals) and actuals[p.interval] is not None:
            p.actual = float(actuals[p.interval])
            err = p.actual - p.p50
            db.add(models.ForecastError(
                kind=kind, trade_date=trade_date, interval=p.interval,
                forecast=p.p50, actual=p.actual, error=err,
                pct_error=err / p.p50 if p.p50 else None))
            n += 1
    db.commit()
    return n
